[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]

[test.workflows]
timeout = 300
cpu = []
gpu = "all"

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
