python = "3.11"

[cuda]
packages = ["torch", "torchvision", "detectron2", "torch-scatter", "torch-sparse", "torch-cluster", "flash-attn"]

[pypi-dependencies]
bpy = ">=4.2"
trimesh = { version = "*", extras = ["easy"] }
numpy = ">=1.21.0,<2.0.0"
pillow = ">=9.0.0"
opencv-python-headless = ">=4.8.0"
huggingface-hub = ">=0.16.0"
transformers = ">=4.30.0"
xtcocotools = ">=1.14"
pytorch-lightning = ">=2.0.0"
pyrender = ">=0.1.45"
yacs = ">=0.1.8"
scikit-image = ">=0.19.0"
einops = ">=0.6.0"
timm = ">=0.9.0"
dill = ">=0.3.6"
pandas = ">=1.5.0"
rich = ">=13.0.0"
hydra-core = ">=1.3.0"
hydra-submitit-launcher = ">=1.2.0"
hydra-colorlog = ">=1.2.0"
pyrootutils = ">=1.0.4"
webdataset = ">=0.2.0"
chump = ">=1.6.0"
networkx = "==3.2.1"
roma = ">=1.3.0"
joblib = ">=1.2.0"
seaborn = ">=0.12.0"
wandb = ">=0.15.0"
appdirs = ">=1.4.4"
appnope = ">=0.1.3"
ffmpeg-python = ">=0.2.0"
cython = ">=0.29.0"
jsonlines = ">=3.1.0"
loguru = ">=0.7.0"
optree = ">=0.9.0"
fvcore = ">=0.1.5"
pycocotools = ">=2.0.6"
addict = ">=2.4.0"
psutil = "*"
comfy-aimdo = "*"