python = "3.11"

[cuda]
detectron2 = "*"
torch-scatter = "*"
torch-sparse = "*"
torch-cluster = "*"

[pypi-dependencies]
bpy = ">=4.2"
trimesh = { version = "*", extras = ["easy"] }
numpy = ">=1.21.0,<2.0.0"
pillow = ">=9.0.0"
opencv-python-headless = ">=4.8.0"
huggingface-hub= ">=0.16.0"
transformers= ">=4.30.0"
xtcocotools= ">=1.14"
